### ISSUE TITLE
window is not defined

### ISSUE THREAD

**Issue by nickyoung87** [elter1109/react-input-date-mask#2]
I started getting this error when I refresh the page:

![image](https://user-images.githubusercontent.com/2645164/160188663-e2ecc037-0d6c-40b0-a036-dfcb8a59a6b7.png)

![image](https://user-images.githubusercontent.com/2645164/160188866-a95ed8a2-56dc-4397-a6dc-c42cbedda9f5.png)

This is a next implementation and this is when running locally (haven't tested in a production environment) and it only happens when I do a hard refresh of the page. If I navigate to the page it works fine.

Any thoughts on this?

**Comment by nickyoung87** [comment]
Alright I was finally able to revisit this issue and seem to have got a fix in place. I opened a PR but in case this repo is not managed I will supply my solution here as well.

What I did was just fork the repo and then pull the code from it and create my own `ReactInputDateMask` component inside my project. 

![image](https://user-images.githubusercontent.com/2645164/176563669-bbf93fde-f7a2-4ceb-95a9-24fca8c694a0.png)

I then edited the first line of the util.js to be this instead:
`const ua = typeof window !== "undefined" ? window.navigator?.userAgent ?? "" : "";`

That really is all there was to it. I did also convert it to a React functional component and did the export differently. I am not sure if that is necessary or not, so if it still gives you issues or doesn't work at all you may want to try that.

Hopefully this helps someone out there!

**Comment by elter1109** [comment]
hi @nickyoung87 , sorry for the long answer, unfortunately, at the moment I do not support this project, copying and correcting the code was a great solution, thank you
